<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="AMAC02FP09XQ6LW" failures="112" tests="191" name="AllTests" time="564.1" errors="0" timestamp="2022-05-15T19:03:33 EEST">
  <testcase classname="calculator.TestCases.BasicCalculatorHome" name="OpenHomePage" time="0.049"/>
  <testcase classname="calculator.TestCases.BasicCalculatorHome" name="SelectBuild" time="0.43"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="3.166"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.364"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.613"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.385"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.291"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.283"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.321"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.373">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionIntegerOnly(Addition.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AdditionIntegerOnly -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.586">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionIntegerOnly(Addition.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AdditionIntegerOnly -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.277">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionIntegerOnly(Addition.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AdditionIntegerOnly -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.245"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.306"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.357"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.243"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.514"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.261"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.265">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionIntegerOnly(Addition.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- AdditionIntegerOnly -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.258">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionIntegerOnly(Addition.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- AdditionIntegerOnly -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.237">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionIntegerOnly(Addition.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- AdditionIntegerOnly -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.249"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionIntegerOnly" time="2.22"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.255"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.213"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.221"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.22"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.237"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.219"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.235"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.254"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.254"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.204"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.204"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.199">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionTwoNumber(Addition.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AdditionTwoNumber -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.256">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionTwoNumber(Addition.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AdditionTwoNumber -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.229"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.212">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionTwoNumber(Addition.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AdditionTwoNumber -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.21">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionTwoNumber(Addition.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AdditionTwoNumber -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.201"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.213">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionTwoNumber(Addition.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- AdditionTwoNumber -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.208">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionTwoNumber(Addition.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- AdditionTwoNumber -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.187"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.203"/>
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="3.059">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.289">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.592"/>
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.485">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.259">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.212">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.242"/>
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.403">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.457">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.242">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.24"/>
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.256">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.276">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.271">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.347">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.234"/>
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.241">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.227">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.208">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.22">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionIntegerOnly" time="2.204">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionIntegerOnly(Subtraction.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionIntegerOnly -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.199">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.201">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.201">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.202">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.197">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.205">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.203">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.232">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.219">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.186">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.22"/>
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.203">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.214">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.194"/>
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.214">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.197">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.182"/>
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.197">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.194">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.199">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Subtraction" name="SubtractionTwoNumber" time="2.188">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Subtraction.SubtractionTwoNumber(Subtraction.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- SubtractionTwoNumber -->
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="3.018"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.344"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.708"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.462"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.269"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.236"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.252"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.392">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Multiply.MultiplyIntegerOnly(Multiply.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyIntegerOnly -->
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.446">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Multiply.MultiplyIntegerOnly(Multiply.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyIntegerOnly -->
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.226">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Multiply.MultiplyIntegerOnly(Multiply.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyIntegerOnly -->
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.213"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.259"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.267"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.256"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.349"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.244"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.225">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Multiply.MultiplyIntegerOnly(Multiply.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyIntegerOnly -->
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.224">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Multiply.MultiplyIntegerOnly(Multiply.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyIntegerOnly -->
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.208">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Multiply.MultiplyIntegerOnly(Multiply.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyIntegerOnly -->
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.216"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyIntegerOnly" time="2.316"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.241"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.205"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.207"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.217"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.225"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.221"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.208"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.25"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.222"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.218"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.245"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.198">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Multiply.MultiplyTwoNumber(Multiply.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyTwoNumber -->
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.204">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Multiply.MultiplyTwoNumber(Multiply.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyTwoNumber -->
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.207"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.196">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Multiply.MultiplyTwoNumber(Multiply.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyTwoNumber -->
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.216">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Multiply.MultiplyTwoNumber(Multiply.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyTwoNumber -->
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.199"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.216">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Multiply.MultiplyTwoNumber(Multiply.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyTwoNumber -->
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.19">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Multiply.MultiplyTwoNumber(Multiply.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyTwoNumber -->
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.198"/>
  <testcase classname="calculator.TestCases.Multiply" name="MultiplyTwoNumber" time="2.207"/>
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="3.041">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="2.281">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="2.553">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="2.483">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="2.251">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="2.214">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="2.24"/>
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="2.374">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="2.446">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="2.236">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="2.248"/>
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="2.246">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="2.263">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="2.237">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="2.258">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:678)
at java.base/java.lang.Integer.parseInt(Integer.java:786)
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="15.265">
    <failure type="org.openqa.selenium.ElementNotInteractableException" message="element not interactable
  (Session info: chrome=101.0.4951.64)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;AMAC02FP09XQ6LW&amp;apos;, ip: &amp;apos;fe80:0:0:0:1838:8ea7:ae57:f196%en0&amp;apos;, os.name: &amp;apos;Mac OS X&amp;apos;, os.arch: &amp;apos;x86_64&amp;apos;, os.version: &amp;apos;12.3.1&amp;apos;, java.version: &amp;apos;17.0.1&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.64, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /var/folders/7h/07jr07q90sb...}, goog:chromeOptions: {debuggerAddress: localhost:62594}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 7131e4534b06986b0789233c619eca05">
      <![CDATA[org.openqa.selenium.ElementNotInteractableException: element not interactable
  (Session info: chrome=101.0.4951.64)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'AMAC02FP09XQ6LW', ip: 'fe80:0:0:0:1838:8ea7:ae57:f196%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.3.1', java.version: '17.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.64, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /var/folders/7h/07jr07q90sb...}, goog:chromeOptions: {debuggerAddress: localhost:62594}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 7131e4534b06986b0789233c619eca05
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.click(Unknown Source)
at calculator.pages.BasicCalculatorPage.performOperationInteger(BasicCalculatorPage.java:81)
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="15.234">
    <failure type="org.openqa.selenium.ElementNotInteractableException" message="element not interactable
  (Session info: chrome=101.0.4951.64)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;AMAC02FP09XQ6LW&amp;apos;, ip: &amp;apos;fe80:0:0:0:1838:8ea7:ae57:f196%en0&amp;apos;, os.name: &amp;apos;Mac OS X&amp;apos;, os.arch: &amp;apos;x86_64&amp;apos;, os.version: &amp;apos;12.3.1&amp;apos;, java.version: &amp;apos;17.0.1&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.64, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /var/folders/7h/07jr07q90sb...}, goog:chromeOptions: {debuggerAddress: localhost:62594}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 7131e4534b06986b0789233c619eca05">
      <![CDATA[org.openqa.selenium.ElementNotInteractableException: element not interactable
  (Session info: chrome=101.0.4951.64)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'AMAC02FP09XQ6LW', ip: 'fe80:0:0:0:1838:8ea7:ae57:f196%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.3.1', java.version: '17.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.64, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /var/folders/7h/07jr07q90sb...}, goog:chromeOptions: {debuggerAddress: localhost:62594}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 7131e4534b06986b0789233c619eca05
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.click(Unknown Source)
at calculator.pages.BasicCalculatorPage.performOperationInteger(BasicCalculatorPage.java:81)
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="15.184">
    <failure type="org.openqa.selenium.ElementNotInteractableException" message="element not interactable
  (Session info: chrome=101.0.4951.64)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;AMAC02FP09XQ6LW&amp;apos;, ip: &amp;apos;fe80:0:0:0:1838:8ea7:ae57:f196%en0&amp;apos;, os.name: &amp;apos;Mac OS X&amp;apos;, os.arch: &amp;apos;x86_64&amp;apos;, os.version: &amp;apos;12.3.1&amp;apos;, java.version: &amp;apos;17.0.1&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.64, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /var/folders/7h/07jr07q90sb...}, goog:chromeOptions: {debuggerAddress: localhost:62594}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 7131e4534b06986b0789233c619eca05">
      <![CDATA[org.openqa.selenium.ElementNotInteractableException: element not interactable
  (Session info: chrome=101.0.4951.64)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'AMAC02FP09XQ6LW', ip: 'fe80:0:0:0:1838:8ea7:ae57:f196%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.3.1', java.version: '17.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.64, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /var/folders/7h/07jr07q90sb...}, goog:chromeOptions: {debuggerAddress: localhost:62594}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 7131e4534b06986b0789233c619eca05
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.click(Unknown Source)
at calculator.pages.BasicCalculatorPage.performOperationInteger(BasicCalculatorPage.java:81)
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="15.176">
    <failure type="org.openqa.selenium.ElementNotInteractableException" message="element not interactable
  (Session info: chrome=101.0.4951.64)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;AMAC02FP09XQ6LW&amp;apos;, ip: &amp;apos;fe80:0:0:0:1838:8ea7:ae57:f196%en0&amp;apos;, os.name: &amp;apos;Mac OS X&amp;apos;, os.arch: &amp;apos;x86_64&amp;apos;, os.version: &amp;apos;12.3.1&amp;apos;, java.version: &amp;apos;17.0.1&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.64, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /var/folders/7h/07jr07q90sb...}, goog:chromeOptions: {debuggerAddress: localhost:62594}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 7131e4534b06986b0789233c619eca05">
      <![CDATA[org.openqa.selenium.ElementNotInteractableException: element not interactable
  (Session info: chrome=101.0.4951.64)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'AMAC02FP09XQ6LW', ip: 'fe80:0:0:0:1838:8ea7:ae57:f196%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.3.1', java.version: '17.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.64, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /var/folders/7h/07jr07q90sb...}, goog:chromeOptions: {debuggerAddress: localhost:62594}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 7131e4534b06986b0789233c619eca05
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.click(Unknown Source)
at calculator.pages.BasicCalculatorPage.performOperationInteger(BasicCalculatorPage.java:81)
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="15.217">
    <failure type="org.openqa.selenium.ElementNotInteractableException" message="element not interactable
  (Session info: chrome=101.0.4951.64)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;AMAC02FP09XQ6LW&amp;apos;, ip: &amp;apos;fe80:0:0:0:1838:8ea7:ae57:f196%en0&amp;apos;, os.name: &amp;apos;Mac OS X&amp;apos;, os.arch: &amp;apos;x86_64&amp;apos;, os.version: &amp;apos;12.3.1&amp;apos;, java.version: &amp;apos;17.0.1&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.64, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /var/folders/7h/07jr07q90sb...}, goog:chromeOptions: {debuggerAddress: localhost:62594}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 7131e4534b06986b0789233c619eca05">
      <![CDATA[org.openqa.selenium.ElementNotInteractableException: element not interactable
  (Session info: chrome=101.0.4951.64)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'AMAC02FP09XQ6LW', ip: 'fe80:0:0:0:1838:8ea7:ae57:f196%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.3.1', java.version: '17.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.64, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /var/folders/7h/07jr07q90sb...}, goog:chromeOptions: {debuggerAddress: localhost:62594}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 7131e4534b06986b0789233c619eca05
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.click(Unknown Source)
at calculator.pages.BasicCalculatorPage.performOperationInteger(BasicCalculatorPage.java:81)
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideIntegerOnly" time="15.186">
    <failure type="org.openqa.selenium.ElementNotInteractableException" message="element not interactable
  (Session info: chrome=101.0.4951.64)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;AMAC02FP09XQ6LW&amp;apos;, ip: &amp;apos;fe80:0:0:0:1838:8ea7:ae57:f196%en0&amp;apos;, os.name: &amp;apos;Mac OS X&amp;apos;, os.arch: &amp;apos;x86_64&amp;apos;, os.version: &amp;apos;12.3.1&amp;apos;, java.version: &amp;apos;17.0.1&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.64, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /var/folders/7h/07jr07q90sb...}, goog:chromeOptions: {debuggerAddress: localhost:62594}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 7131e4534b06986b0789233c619eca05">
      <![CDATA[org.openqa.selenium.ElementNotInteractableException: element not interactable
  (Session info: chrome=101.0.4951.64)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'AMAC02FP09XQ6LW', ip: 'fe80:0:0:0:1838:8ea7:ae57:f196%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.3.1', java.version: '17.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.64, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /var/folders/7h/07jr07q90sb...}, goog:chromeOptions: {debuggerAddress: localhost:62594}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 7131e4534b06986b0789233c619eca05
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.click(Unknown Source)
at calculator.pages.BasicCalculatorPage.performOperationInteger(BasicCalculatorPage.java:81)
at calculator.TestCases.Divide.DivideIntegerOnly(Divide.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- DivideIntegerOnly -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.753">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.68">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.433">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.485">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.399">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.427">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.446"/>
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.437">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.416">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.413">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.454"/>
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.399">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.432">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.409">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.411">
    <failure type="java.lang.NumberFormatException" message="empty String">
      <![CDATA[java.lang.NumberFormatException: empty String
at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.base/java.lang.Double.parseDouble(Double.java:651)
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.407"/>
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.453">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.426">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.411">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.417">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Divide" name="DivideTwoNumber" time="2.458">
    <failure type="java.lang.NumberFormatException" message="empty String">
      <![CDATA[java.lang.NumberFormatException: empty String
at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.base/java.lang.Double.parseDouble(Double.java:651)
at calculator.TestCases.Divide.DivideTwoNumber(Divide.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DivideTwoNumber -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.907">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.292">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.277">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.493">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.357">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.206">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.218"/>
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.249">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.199">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.222">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.679">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.366">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.258">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.205">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.185">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.207">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.267">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Concatenate.ConcatenateTwoValues(Concatenate.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- ConcatenateTwoValues -->
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.39"/>
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.205"/>
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.192"/>
  <testcase classname="calculator.TestCases.Concatenate" name="ConcatenateTwoValues" time="2.196"/>
</testsuite> <!-- AllTests -->
