<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="5CG0281XKR" failures="4" tests="17" name="ParallelTest" time="107.774" errors="0" timestamp="2022-05-11T00:03:04 EEST">
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.897"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.936"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.716"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.751"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.693"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.638"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.68"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.66"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.841"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.698"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.75"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.619">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionTwoNumber(Addition.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AdditionTwoNumber -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.756">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionTwoNumber(Addition.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AdditionTwoNumber -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.656"/>
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.611">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionTwoNumber(Addition.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AdditionTwoNumber -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.617">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at calculator.TestCases.Addition.AdditionTwoNumber(Addition.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AdditionTwoNumber -->
  <testcase classname="calculator.TestCases.Addition" name="AdditionTwoNumber" time="2.631"/>
</testsuite> <!-- ParallelTest -->
